### ISSUE TITLE
vs2017 support?

### ISSUE THREAD

**Issue by Muscipular** [iccfish/indent-guides-mod#1]

**Comment by iccfish** [comment]
VS2017 has native support for indent guide, does it satisfy you?

**Comment by Muscipular** [comment]
vs2017 native indent guide does not support js/css

**Comment by iccfish** [comment]
VS2017 native indent guide does support js but not css. If support for css was really need, I'll consider to add support for vs2017.

Thanks for your advice. 😄

**Comment by iccfish** [comment]
Extension for VS2017 has been released via https://marketplace.visualstudio.com/items?itemName=ccfish.IndentGuides.

Vsiual Studio 2017 Update 3(15.3) tested.

**Comment by iccfish** [comment]
Sorry for there's some issue need to be resolved.

**Comment by iccfish** [comment]
Finally I rememberd this and release [IndentGuide for VS2017/2019](https://marketplace.visualstudio.com/items?itemName=ccfish.indentguides-mod), sorry...

**Comment by Thieum** [comment]
@iccfish I took inspiration from what you have done to [fix the original package](https://github.com/zooba/indentguide/pull/11). It is now on GitHub, so if you have other improvements or fixes maybe it would be easier to share efforts.
